AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ApiName:
    Description: Name of the API
    Type: String

  ApiSchema:
    Description: Name of the API Schema
    Type: String

  SchemaLoc:
    Description: S3 location of the Api Schema
    Type: String


Resources:
  GraphQLApi:
    Type: AWS::AppSync::GraphQLApi
    Properties:
      AuthenticationType: API_KEY
      Name: !Ref ApiName
      Tags:
        - Key: Project
          Value: teamreports  
  
  GraphQLSchema:
    Type: AWS::AppSync::GraphQLSchema
    Properties:
      ApiId: !GetAtt GraphQLApi.ApiId
      DefinitionS3Location: !Ref SchemaLoc

Outputs:
  GraphQLApiUrl:
    Description: GraphQL Api URL
    Value: !GetAtt GraphQLApi.GraphQLUrl

