AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ApiName:
    Description: Name of the API
    Type: String

Resources:
  GraphQLApi:
    Type: AWS::AppSync::GraphQLApi
    Properties:
      AuthenticationType: API_KEY
      Name: !Ref ApiName
      Tags:
        - Key: Project
          Value: teamreports  
  
  GraphQLSchema:
    Type: AWS::AppSync::GraphQLSchema
    Properties:
      ApiId: !GetAtt GraphQLApi.ApiId
      Definition: 
        Transform:
          Name: AWS::Include
          Parameters:
            Location: file://teamreportsapi-schema.graphql

Outputs:
  GraphQLApiUrl:
      Description: GraphQL Api URL
      Value: !GetAtt GraphQLApi.GraphQLUrl

