AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ApiName:
    Description: Name of the API
    Type: String
    # Default: gapi

  ApiSchema:
    Description: Name of the API Schema
    Type: String
    # Default: gschema

  buildBucketName:
    Description: CodeBuild output bucket name - will be injected by CodePipeline Parameter overrides (to be configured)
    Type: String
    # Default: anewbucket

  buildObjectKey:
    Description: S3 object key for the artifact generated in the CodeBuild output bucket - will be injected by CodePipeline Parameter overrides (to be configured)
    Type: String 
    # Default: anewkey

  s3OutputUrl:
    Type: String
    # Default: anewoutput

Resources:
  GraphQLApi:
    Type: AWS::AppSync::GraphQLApi
    Properties:
      AuthenticationType: API_KEY
      Name: !Ref ApiName
      Tags:
        - Key: Project
          Value: teamreports  
  
  # GraphQLSchema:
  #   Type: AWS::AppSync::GraphQLSchema
  #   Properties:
  #     ApiId: !GetAtt GraphQLApi.ApiId
  #     DefinitionS3Location: !Sub "s3://${buildBucketName}/firstpipeline/BuildArtif/${buildObjectKey}/backend/api/${ApiSchema}"

Outputs:
  GraphQLApiUrl:
    Description: GraphQL Api URL
    Value: !GetAtt GraphQLApi.GraphQLUrl
  
  BuiltOutputBucketName:
    Description: buildBucketName
    Value: !Ref buildBucketName

  BuiltOutputObjectKey:
    Description: buildObjectKey
    Value: !Ref buildObjectKey

  s3OutputUrl:
    Value: !Ref s3OutputUrl    

  builtValue:
    Value: !Sub
        - s3://${buildBucketName}/firstpipeline/BuildArtif/${buildObjectKey}/backend/api/${ApiSchema}
        - { abuildBucketName: !Ref buildBucketName, abuildObjectKey: !Ref buildObjectKey, aApiSchema: !Ref ApiSchema }

