version: 0.2

phases:
  install:
    commands:
      - echo No action on install phase...
  pre_build:
    commands:
      - echo No action on pre_build phase...
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build completed on `date`
      - aws s3 cp backend/api/schemas/teamreportsapi-schema.graphql s3://codepipeline-us-east-1-sbabs-user/teamreports/dev/ 
artifacts:
  files:
    - backend/api/**/*
  secondary-artifacts:
    schemas:
      files:
        - backend/api/schemas/teamreportsapi-schema.graphql
      name: graphql-schemas