version: 0.2

phases:
  install:
    commands:
      - echo No action on install step...
  pre_build:
    commands:
      - echo Upload API spec to S3 bucket...
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - backend/api/teamreportsapi-schema.graphql