Parameters:
  OrgId:
    Description: Org Id
    Type: String
    Default: agilevision

Resources:
  TeamReportsUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Join
        - '-'
        - - !Ref OrgId
          - 'teamreports-userpool'
      Policies:
        PasswordPolicy:
          MinimumLength: 8
      UsernameAttributes:
        - email
      Schema:
        - AttributeDataType: String
          Name: email
          Required: false
      UserPoolTags:
        {
          "Project": "TeamReports"
        }

  TeamReportsUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref TeamReportsUserPool
      ClientName: !Join
        - '-'
        - - !Ref OrgId
          - 'teamreports-webapp'
      GenerateSecret: false

