AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  reports-bloom-onboard-app
  
Globals:
  Function:
    Timeout: 30

Resources:
  DomainCheckFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions
      Handler: domaincheck.lambdaHandler
      Runtime: nodejs12.x

  Route53EventsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions
      Handler: route53events.lambdaHandler
      Runtime: nodejs12.x      

Outputs:
  DomainCheckFunction:
    Description: "Domain Check Lambda Function ARN"
    Value: !GetAtt DomainCheckFunction.Arn
  DomainCheckFunctionIamRole:
    Description: "Implicit IAM Role created for Domain Check function"
    Value: !GetAtt DomainCheckFunction.Arn
