AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  reports-bloom-onboard-app

Parameters:
  lifecycle:
    Type: String
    Default: dev

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs12.x
    Environment:
      Variables:
        lifecycle: !Ref lifecycle
        region: us-east-1

Resources:
  DomainCheckFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions
      Handler: domaincheck.lambdaHandler

  Route53EventsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions
      Handler: route53events.lambdaHandler
      Policies:
        - Statement:
            - Sid: SSMGetParameterPolicy
              Effect: Allow
              Action:
                - ssm:PutParameter
                - ssm:PutParameters
                - ssm:GetParameter
                - ssm:GetParameters
                - ssm:AddTagsToResource
              Resource: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/*.com./${lifecycle}/*

Outputs:
  DomainCheckFunction:
    Description: 'Domain Check Lambda Function ARN'
    Value: !GetAtt DomainCheckFunction.Arn
  DomainCheckFunctionIamRole:
    Description: 'Implicit IAM Role created for Domain Check function'
    Value: !GetAtt DomainCheckFunction.Arn
